FROM python:3.7.4-alpine

WORKDIR /usr/src/app

RUN pip install --upgrade pip==10.0.1
RUN apk update && apk add \
  curl \
  gcc \
  gettext \
  git \
  make \
  musl-dev \
  postgresql-dev \
  tini

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python", "-u", "./run.py" ]
